name: Scrape users data from JSONPlaceholder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://jsonplaceholder.typicode.com/users | jq . > users.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Bakary"
        git config user.email "bakaryseydou@gmail.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "users data from JSONPlacehoder online rest api : ${timestamp}" || exit 0
        git push
